import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

import { createClient } from 'contentful';

import { Button, Accordion, Icon, Segment } from 'semantic-ui-react'
import AnimateHeight from 'react-animate-height';

const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
});

export async function getStaticPaths() {
    const res = await client.getEntries({
        content_type: "unit",
        select: ['fields.unitNumber', 'fields.course'].join(',')
    });

    return {
        paths: res.items.map(item => ({ params: { course: item.fields.course.fields.slug, unit: "unit-"+item.fields.unitNumber } })),
        fallback: true,
    }
}

export async function getStaticProps({ params }) {
    const res = await client.getEntries({
        content_type: "unit",
        'fields.unitNumber': params.unit.split("-")[1]
    });

    return {
        props: {
            unit: res.items[0],
            revalidate: 30
        }
    }

}

export default function Unit({ unit }) {return (
        <>
            <Head>
                <title>{"Learnit - Unit" + unit.fields.unitNumber + ": " + unit.fields.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="page_body">
                <Link href={"/"+unit.fields.course.fields.slug}>
                    <Button icon labelPosition='left'>
                        <Icon name='left arrow' />
                        Back
                    </Button>
                </Link>
                <h1>Unit {unit.fields.unitNumber} - {unit.fields.title}</h1>
            </div>
        </>
    )
}
