import Head from 'next/head'
//import Image from 'next/image'
import { useUser } from '@auth0/nextjs-auth0';
import { Icon, Button, Grid } from 'semantic-ui-react';

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Head>
        <title>Learnit - Library</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="dashboard">
          <h1>{user?.name || "Guest"}</h1>
          <p><b>Experience Points:</b> 0 <Icon name="magic" color="yellow" /></p>
          <p><b>Season Points:</b> 0 <Icon name="star" color="yellow" /></p>
        </div>
        <div class="page_body">
          <Grid celled='internally'>
            <Grid.Row>
              <Grid.Column width={10}>
                <h2>Assignments</h2>
                <p>No assignments have been posted by your instructors.</p>
                <h2>Your Courses</h2>
                <p>You are not enrolled in any courses.</p>
                <p><Button color="orange" content='Add Course' icon='plus' labelPosition='left' /></p>
              </Grid.Column>
              <Grid.Column width={6}>
                <h2>Today's Tasks</h2>
                <h2>Daily Mastery Quiz</h2>
                <p>Come back in $time for your next quiz!</p>
              </Grid.Column>
            </Grid.Row>
          </Grid>
        </div>
      </div>
    </>
  )
}
